#!/usr/bin/env Rscript
# Apply the four-level annotation generated by
# 18_make_cluster_annotation_helper_table.R to the Seurat object.

suppressPackageStartupMessages({
  library(Seurat)
  library(data.table)
  library(ggplot2)
})

outDir <- "06.multiome/04.seurat_signac"
objFile <- file.path(outDir, "FMdeer_multiome.wnn.robust.markers.rds")
annoFile <- file.path(outDir, "cluster_annotation_helper_table.tsv")

if (!file.exists(objFile)) stop("Missing object: ", objFile)
if (!file.exists(annoFile)) stop("Missing annotation table: ", annoFile)

obj <- readRDS(objFile)
anno <- fread(annoFile, sep = "\t", header = TRUE)

if (!"seurat_clusters" %in% colnames(obj@meta.data)) {
  stop("seurat_clusters not found in object metadata.")
}
if (!"cluster" %in% colnames(anno)) {
  stop("annotation table must contain a 'cluster' column")
}

Idents(obj) <- "seurat_clusters"
anno[, cluster := as.character(cluster)]

# Script 18 writes detailed/minor/major/state columns. Old tables containing
# only final_celltype or suggested_celltype remain supported.
empty_or_missing <- function(x) is.na(x) | x == ""
for (cc in c("celltype_detailed", "celltype_minor", "celltype_major", "cell_state",
             "suggested_celltype", "final_celltype")) {
  if (!cc %in% colnames(anno)) anno[, (cc) := NA_character_]
  anno[, (cc) := as.character(get(cc))]
}

anno[empty_or_missing(celltype_detailed) & !empty_or_missing(suggested_celltype),
     celltype_detailed := suggested_celltype]
anno[empty_or_missing(celltype_detailed) & !empty_or_missing(final_celltype),
     celltype_detailed := final_celltype]
anno[empty_or_missing(celltype_detailed), celltype_detailed := paste0("Cluster_", cluster)]
anno[empty_or_missing(celltype_minor), celltype_minor := celltype_detailed]
anno[empty_or_missing(celltype_major) & !empty_or_missing(final_celltype),
     celltype_major := final_celltype]
anno[empty_or_missing(celltype_major), celltype_major := celltype_minor]
anno[empty_or_missing(cell_state), cell_state := "None_detected"]

# final_celltype is editable in the helper table. Use its value as the legacy
# celltype column, but retain standardized major lineages in celltype_major.
anno[empty_or_missing(final_celltype), final_celltype := celltype_major]

apply_map <- function(column) {
  unname(as.character(setNames(anno[[column]], anno$cluster)[as.character(Idents(obj))]))
}

obj@meta.data$celltype_detailed <- apply_map("celltype_detailed")
obj@meta.data$celltype_minor <- apply_map("celltype_minor")
obj@meta.data$celltype_major <- apply_map("celltype_major")
obj@meta.data$cell_state <- apply_map("cell_state")
obj@meta.data$celltype <- apply_map("final_celltype") # backward compatibility

level_source <- c(
  celltype_detailed = "celltype_detailed",
  celltype_minor = "celltype_minor",
  celltype_major = "celltype_major",
  cell_state = "cell_state",
  celltype = "final_celltype"
)
for (cc in names(level_source)) {
  obj@meta.data[[cc]] <- factor(obj@meta.data[[cc]], levels = unique(anno[[level_source[[cc]]]]))
}

meta <- obj@meta.data
meta$cell <- rownames(meta)
fwrite(as.data.table(meta), file.path(outDir, "cell_metadata_with_annotation_levels.tsv"), sep = "\t")

if (!"wnn.umap" %in% Reductions(obj)) {
  warning("wnn.umap not found; annotation metadata will be saved without UMAP plots.")
} else {
  pdf(file.path(outDir, "07_annotation_levels_UMAP.pdf"), width = 14, height = 10)
  print(DimPlot(obj, reduction = "wnn.umap", group.by = "celltype_major", label = TRUE, repel = TRUE) +
          ggtitle("WNN UMAP by merged major cell types"))
  print(DimPlot(obj, reduction = "wnn.umap", group.by = "celltype_minor", label = TRUE, repel = TRUE) +
          ggtitle("WNN UMAP by minor cell types"))
  print(DimPlot(obj, reduction = "wnn.umap", group.by = "cell_state", label = TRUE, repel = TRUE) +
          ggtitle("WNN UMAP by cell state"))
  print(DimPlot(obj, reduction = "wnn.umap", group.by = "seurat_clusters", label = TRUE, repel = TRUE) +
          ggtitle("WNN UMAP by cluster"))
  if ("sample" %in% colnames(obj@meta.data)) {
    print(DimPlot(obj, reduction = "wnn.umap", group.by = "sample") + ggtitle("WNN UMAP by sample"))
  }
  dev.off()
}

# Use major lineage for sample composition, keeping stress/cycling as cell_state.
if ("sample" %in% colnames(obj@meta.data)) {
  ct_sample <- as.data.table(table(obj@meta.data$celltype_major, obj@meta.data$sample))
  setnames(ct_sample, c("celltype_major", "sample", "n_cells"))
  fwrite(ct_sample, file.path(outDir, "major_celltype_by_sample_counts.final.tsv"), sep = "\t")
}

saveRDS(obj, file.path(outDir, "FMdeer_multiome.wnn.final_annotated.rds"))
message("Done.")
